[upstream]
source = "web"

[mirror]
url = [
	"mirror://revyos/extra/images/meles/",
]

[packages]
board-image = [
	"revyos-milkv-meles",
	"uboot-revyos-milkv-meles-4g",
	"uboot-revyos-milkv-meles-8g",
	"uboot-revyos-milkv-meles-16g",
]

# [policies]
# uboot-revyos-milkv-meles-4g = ["keep_back"]
# uboot-revyos-milkv-meles-8g = ["keep_back"]
# uboot-revyos-milkv-meles-16g = ["keep_back"]
