[upstream]
source = "web"

[mirror]
url = [
	"mirror://ubuntu-cdimage/releases/",
	"mirror://ubuntu-old-releases/releases/",
]

[packages]
board-image = [
	"ubuntu-server-riscv64-sifive-unmatched",
]
